# TODO
# - implement graphical elements & rendering
# - handle game complete
# - hanlde moving the camera
# - reset the game
# - handle the shineness

direction: right

# Systems
classes: {
  Entity: {
    width: 800
    style: {
      stroke-width: 0
      fill: "#FFD700" # orange yellow
      border-radius: 5
    }
  }

  Component: {
    width: 600
    style: {
      stroke-width: 0
      fill: "#44C7B1" # pastel green
      border-radius: 5
    }
  }

  System: {
    width: 1000
    style: {
      stroke-width: 0
      fill: "#87CEEB" # sky blue
      border-radius: 5
    }
  }
}

# Entity & Components
PlayerEntity: {
  label: Player
  class: Entity

  CameraComponent: {
    class: Component
    shape: class

    + position: Vec3
    + front: Vec3
    + up: Vec3
  }

  CleanerComponent: {
    class: Component
    shape: class

    + active: bool
    + radius: float
    + screenPoint: Vec2i
  }
}

WashableEntity: {
  label: Washable
  class: Entity
}

WashablePartEntity: {
  label: WashablePart
  class: Entity

  DirtyMapComponent: {
    class: Component
    shape: class

    + cleanness: float
    + texture: "float[][]"
  }

  RenderComponent: {
    class: Component
    shape: class

    # TODO
  }
}

Client

GameEntity: {
  label: Game
  class: Entity

  GameStateComponent: {
    class: Component
    shape: class

    + state: playing | completed
    + completeness: float
  }

  EventQueueComponent: {
    class: Component
    shape: class

    + events: "Event[]"
  }

  CanvasComponent: {
    class: Component
    shape: class

    + width: int
    + height: int
  }
}

# Relationships
WashablePartEntity -> WashableEntity: included

# Systems
Systems: {
  InteractSystem: {
    class: System
    shape: class

    + startGame(EventQueueComponent): void
    + pointDown(EventQueueComponent): void
    + pointMove(EventQueueComponent): void
    + pointUp(EventQueueComponent): void
  }

  EventSystem: {
    class: System
    shape: class

    + consumeEvents(EventQueueComponent, GameStateComponent, CleanerComponent): void
  }

  CleanSystem: {
    class: System
    shape: class

    + clean(CleanerComponent, CameraComponent, DirtyMapComponent\[\]): void
  }

  CalculateSystem: {
    class: System
    shape: class

    + calculateCompleteness(DirtyMapComponent\[\], GameStateComponent): void
  }

  RenderSystem: {
    class: System
    shape: class

    + render(CanvasComponent, RenderComponent\[\]): void
  }

  FeedbackSystem: {
    class: System
    shape: class

    + setTotalCompleteness(GameStateComponent): void
  }
}

# Relationships
Client -> Systems.InteractSystem
Systems.InteractSystem -> GameEntity.EventQueueComponent
Systems.EventSystem <- GameEntity.EventQueueComponent
Systems.EventSystem -> GameEntity.GameStateComponent
Systems.EventSystem -> PlayerEntity.CleanerComponent
Systems.CleanSystem <- PlayerEntity.CleanerComponent
Systems.CleanSystem <- PlayerEntity.CameraComponent
Systems.CleanSystem <- WashablePartEntity.RenderComponent
Systems.CleanSystem -> WashablePartEntity.DirtyMapComponent
Systems.CalculateSystem <- WashablePartEntity.DirtyMapComponent
Systems.CalculateSystem -> GameEntity.GameStateComponent
Systems.RenderSystem <- GameEntity.CanvasComponent
Systems.RenderSystem <- WashablePartEntity.RenderComponent
Client <- Systems.RenderSystem
Systems.FeedbackSystem <- GameEntity.GameStateComponent
Client <- Systems.FeedbackSystem
