Rendering Process: {
  shape: sequence_diagram
  DataComponents
  Systems
  GrComponents: GraphicResourceComponents
  RenderSystem
  Canvas

  Initialize Graphic API Context: {
    DataComponents -> RenderSystem
    RenderSystem -> Canvas
  }

  Initialize Graphic Resources: {
    DataComponents -> Systems
    Systems -> GrComponents
  }

  Update Graphic Resources: {
    DataComponents."if needs_update = true"
    DataComponents -> Systems
    Systems -> GrComponents
  }

  Render Meshes: {
    GrComponents -> RenderSystem
    RenderSystem -> Canvas
  }
}
